CREATE TABLE IF NOT EXISTS posts (
    id SERIAL PRIMARY KEY,
    full_id VARCHAR(255),
    created TIMESTAMP,
    edited TIMESTAMP,
    permalink TEXT,
    url TEXT,
    title TEXT,
    body TEXT,
    likes BOOLEAN,
    score INT,
    upvote_ratio REAL,
    number_of_comments INT,
    subreddit_name VARCHAR(255),
    subreddit_name_prefixed VARCHAR(255),
    subreddit_id VARCHAR(255),
    subreddit_subscribers INT,
    author VARCHAR(255),
    author_id VARCHAR(255),
    spoiler BOOLEAN,
    locked BOOLEAN,
    nsfw BOOLEAN,
    is_self_post BOOLEAN,
    saved BOOLEAN,
    stickied BOOLEAN
    posted BOOLEAN
);